"use client"
import localFont from "next/font/local";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "../../components/UI/Header/Header";
import Footer from "../../components/UI/Footer/Footer";
import { ProviderWrapper } from "../../components/Provider";
import { useEffect, useState } from "react";
import LoadingPage from "../../components/UI/Loading";
import { title } from "./tiltle";
// import "bootstrap-icons/font/bootstrap-icons.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(()=>{
    document.title= title.title
  },[])
  const [loading, setLoading]= useState(true)

  useEffect(()=>{
    const timeout= setTimeout(()=>{
      setLoading(false)
    }, 2000)
    return ()=> clearTimeout(timeout)
  },[])
  return (
    <ProviderWrapper>
    <html lang="en">
      <body
 className="page-container"
      >
         <Header/>
         {loading ? <LoadingPage/>:
        <div className="content-wrap">
       
        {children}
       
        </div>}
        <Footer/>
      </body>
    </html>
    </ProviderWrapper>
  );
}
